#ifndef MECHANISM_H
#define MECHANISM_H

#include <AMReX_Gpu.H>
#include <AMReX_REAL.H>

/* Elements
0  O
1  H
2  C
3  N
*/

// Species
#define O2_ID 0
#define H2O_ID 1
#define CH4_ID 2
#define CO2_ID 3
#define N2_ID 4

#define NUM_GAS_ELEMENTS 4  // Elements in the homogeneous phase
#define NUM_GAS_SPECIES 5   // Species in the homogeneous phase
#define NUM_GAS_REACTIONS 1 // Reactions in the homogeneous phase

#define SITE_DENSITY 0.000000E+00 // mol/cm^2

#define NUM_SURFACE_ELEMENTS 0  // Additional elements in heterogeneous phase
#define NUM_SURFACE_SPECIES 0   // Species in the heterogeneous phase
#define NUM_SURFACE_REACTIONS 0 // Reactions in the heterogeneous phase

#define NUM_ELEMENTS (NUM_GAS_ELEMENTS + NUM_SURFACE_ELEMENTS)
#define NUM_SPECIES (NUM_GAS_SPECIES + NUM_SURFACE_SPECIES)
#define NUM_REACTIONS (NUM_GAS_REACTIONS + NUM_SURFACE_REACTIONS)

#define NUM_IONS 0

#define NUM_FIT 4

//  ALWAYS on CPU stuff -- can have different def depending on if we are CPU or
//  GPU based. Defined in mechanism.cpp MISC
void CKSYME_STR(amrex::Vector<std::string>& ename);
void CKSYMS_STR(amrex::Vector<std::string>& kname);
void GET_RMAP(int* _rmap);
void CKINU(const int i, int& nspec, int* ki, int* nu);
void CKKFKR(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real* x,
  amrex::Real* q_f,
  amrex::Real* q_r);
void progressRateFR(
  amrex::Real* q_f, amrex::Real* q_r, amrex::Real* sc, amrex::Real T);
//  SPARSE INFORMATION
void SPARSITY_INFO(int* nJdata, const int* consP, int NCELLS);
void SPARSITY_INFO_SYST(int* nJdata, const int* consP, int NCELLS);
void SPARSITY_INFO_SYST_SIMPLIFIED(int* nJdata, const int* consP);
void
SPARSITY_PREPROC_CSC(int* rowVals, int* colPtrs, const int* consP, int NCELLS);
void SPARSITY_PREPROC_CSR(
  int* colVals, int* rowPtrs, const int* consP, int NCELLS, int base);
void SPARSITY_PREPROC_SYST_CSR(
  int* colVals, int* rowPtrs, const int* consP, int NCELLS, int base);
void SPARSITY_PREPROC_SYST_SIMPLIFIED_CSC(
  int* rowVals, int* colPtrs, int* indx, const int* consP);
void SPARSITY_PREPROC_SYST_SIMPLIFIED_CSR(
  int* colVals, int* rowPtr, const int* consP, int base);

// A few mechanism parameters
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKINDX(int& mm, int& kk, int& ii, int& nfit)
{
  mm = 4;
  kk = 5;
  ii = 1;
  nfit = -1; // Why do you need this anyway ?
}

// save atomic weights into array
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
atomicWeight(amrex::Real* awt)
{
  awt[0] = 15.999000; // O
  awt[1] = 1.008000;  // H
  awt[2] = 12.011000; // C
  awt[3] = 14.007000; // N
}

// get atomic weight for all elements
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKAWT(amrex::Real* awt)
{
  atomicWeight(awt);
}

// Returns the elemental composition
// of the speciesi (mdim is num of elements)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKNCF(int* ncf)
{
  int kd = 4;
  // Zero ncf
  for (int id = 0; id < kd * 5; ++id) {
    ncf[id] = 0;
  }

  // O2
  ncf[0 * kd + 0] = 2; // O

  // H2O
  ncf[1 * kd + 1] = 2; // H
  ncf[1 * kd + 0] = 1; // O

  // CH4
  ncf[2 * kd + 2] = 1; // C
  ncf[2 * kd + 1] = 4; // H

  // CO2
  ncf[3 * kd + 2] = 1; // C
  ncf[3 * kd + 0] = 2; // O

  // N2
  ncf[4 * kd + 3] = 2; // N
}

//  inverse molecular weights
#ifdef AMREX_USE_GPU
AMREX_GPU_CONSTANT const amrex::Real global_imw[5] = {
  3.1251953247077940e-02, // O2
  5.5509297807382736e-02, // H2O
  6.2332481456086768e-02, // CH4
  2.2722624917630486e-02, // CO2
  3.5696437495537948e-02, // N2
};
#endif
const amrex::Real h_global_imw[5] = {
  3.1251953247077940e-02, // O2
  5.5509297807382736e-02, // H2O
  6.2332481456086768e-02, // CH4
  2.2722624917630486e-02, // CO2
  3.5696437495537948e-02, // N2
};

//  molecular weights
#ifdef AMREX_USE_GPU
AMREX_GPU_CONSTANT const amrex::Real global_mw[5] = {
  3.1998000000000001e+01, // O2
  1.8015000000000001e+01, // H2O
  1.6042999999999999e+01, // CH4
  4.4009000000000000e+01, // CO2
  2.8013999999999999e+01, // N2
};
#endif
const amrex::Real h_global_mw[5] = {
  3.1998000000000001e+01, // O2
  1.8015000000000001e+01, // H2O
  1.6042999999999999e+01, // CH4
  4.4009000000000000e+01, // CO2
  2.8013999999999999e+01, // N2
};

//  inverse molecular weights
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
get_imw(amrex::Real* imw_new)
{
  imw_new[0] = 3.1251953247077940e-02; // O2
  imw_new[1] = 5.5509297807382736e-02; // H2O
  imw_new[2] = 6.2332481456086768e-02; // CH4
  imw_new[3] = 2.2722624917630486e-02; // CO2
  imw_new[4] = 3.5696437495537948e-02; // N2
}

//  inverse molecular weight
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real
imw(const int n)
{
#if AMREX_DEVICE_COMPILE
  return global_imw[n];
#else
  return h_global_imw[n];
#endif
}
//  molecular weights
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
get_mw(amrex::Real* mw_new)
{
  mw_new[0] = 3.1998000000000001e+01; // O2
  mw_new[1] = 1.8015000000000001e+01; // H2O
  mw_new[2] = 1.6042999999999999e+01; // CH4
  mw_new[3] = 4.4009000000000000e+01; // CO2
  mw_new[4] = 2.8013999999999999e+01; // N2
}

//  molecular weight
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real
mw(const int n)
{
#if AMREX_DEVICE_COMPILE
  return global_mw[n];
#else
  return h_global_mw[n];
#endif
}

//  Returns R, Rc, Patm
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKRP(amrex::Real& ru, amrex::Real& ruc, amrex::Real& pa)
{
  ru = 8.31446261815324e+07;
  ruc = 1.98721558317399615845;
  pa = 1.01325e+06;
}

// compute Cv/R at the given temperature
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
cv_R(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = +2.782456360000000e+00 - 2.996734160000000e-03 * T +
                 9.847302010000000e-06 * T2 - 9.681295090000001e-09 * T3 +
                 3.243728370000000e-12 * T4;
    // species 1: H2O
    species[1] = +3.198635200000000e+00 - 2.036401700000000e-03 * T +
                 6.520341600000000e-06 * T2 - 5.487926900000000e-09 * T3 +
                 1.771968000000000e-12 * T4;
    // species 2: CH4
    species[2] = +4.149114680000000e+00 - 1.366220090000000e-02 * T +
                 4.914539210000000e-05 * T2 - 4.842467670000000e-08 * T3 +
                 1.666034410000000e-11 * T4;
    // species 3: CO2
    species[3] = +1.356813000000000e+00 + 8.984129900000000e-03 * T -
                 7.122063200000000e-06 * T2 + 2.457300800000000e-09 * T3 -
                 1.428854800000000e-13 * T4;
    // species 4: N2
    species[4] = +2.531005280000000e+00 - 1.236609880000000e-04 * T -
                 5.029994330000001e-07 * T2 + 2.435306120000000e-09 * T3 -
                 1.408812350000000e-12 * T4;
  } else {
    // species 0: O2
    species[0] = +2.660960650000000e+00 + 6.563658110000000e-04 * T -
                 1.411496270000000e-07 * T2 + 2.057979350000000e-11 * T3 -
                 1.299134360000000e-15 * T4;
    // species 1: H2O
    species[1] = +1.677038900000000e+00 + 2.973181600000000e-03 * T -
                 7.737688900000000e-07 * T2 + 9.443351400000000e-11 * T3 -
                 4.268999100000000e-15 * T4;
    // species 2: CH4
    species[2] = +6.532622600000000e-01 + 1.002630990000000e-02 * T -
                 3.316612380000000e-06 * T2 + 5.364831380000000e-10 * T3 -
                 3.146967580000000e-14 * T4;
    // species 3: CO2
    species[3] = +3.636511100000000e+00 + 2.741456900000000e-03 * T -
                 9.958975900000000e-07 * T2 + 1.603866600000000e-10 * T3 -
                 9.161985700000000e-15 * T4;
    // species 4: N2
    species[4] = +1.952576370000000e+00 + 1.396900400000000e-03 * T -
                 4.926316030000000e-07 * T2 + 7.860101950000000e-11 * T3 -
                 4.607552040000000e-15 * T4;
  }
}

// compute Cp/R at the given temperature
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
cp_R(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = +3.782456360000000e+00 - 2.996734160000000e-03 * T +
                 9.847302010000000e-06 * T2 - 9.681295090000001e-09 * T3 +
                 3.243728370000000e-12 * T4;
    // species 1: H2O
    species[1] = +4.198635200000000e+00 - 2.036401700000000e-03 * T +
                 6.520341600000000e-06 * T2 - 5.487926900000000e-09 * T3 +
                 1.771968000000000e-12 * T4;
    // species 2: CH4
    species[2] = +5.149114680000000e+00 - 1.366220090000000e-02 * T +
                 4.914539210000000e-05 * T2 - 4.842467670000000e-08 * T3 +
                 1.666034410000000e-11 * T4;
    // species 3: CO2
    species[3] = +2.356813000000000e+00 + 8.984129900000000e-03 * T -
                 7.122063200000000e-06 * T2 + 2.457300800000000e-09 * T3 -
                 1.428854800000000e-13 * T4;
    // species 4: N2
    species[4] = +3.531005280000000e+00 - 1.236609880000000e-04 * T -
                 5.029994330000001e-07 * T2 + 2.435306120000000e-09 * T3 -
                 1.408812350000000e-12 * T4;
  } else {
    // species 0: O2
    species[0] = +3.660960650000000e+00 + 6.563658110000000e-04 * T -
                 1.411496270000000e-07 * T2 + 2.057979350000000e-11 * T3 -
                 1.299134360000000e-15 * T4;
    // species 1: H2O
    species[1] = +2.677038900000000e+00 + 2.973181600000000e-03 * T -
                 7.737688900000000e-07 * T2 + 9.443351400000000e-11 * T3 -
                 4.268999100000000e-15 * T4;
    // species 2: CH4
    species[2] = +1.653262260000000e+00 + 1.002630990000000e-02 * T -
                 3.316612380000000e-06 * T2 + 5.364831380000000e-10 * T3 -
                 3.146967580000000e-14 * T4;
    // species 3: CO2
    species[3] = +4.636511100000000e+00 + 2.741456900000000e-03 * T -
                 9.958975900000000e-07 * T2 + 1.603866600000000e-10 * T3 -
                 9.161985700000000e-15 * T4;
    // species 4: N2
    species[4] = +2.952576370000000e+00 + 1.396900400000000e-03 * T -
                 4.926316030000000e-07 * T2 + 7.860101950000000e-11 * T3 -
                 4.607552040000000e-15 * T4;
  }
}

// compute the g/(RT) at the given temperature
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
gibbs(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real invT = 1.0 / T;
  const amrex::Real logT = log(T);

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = -1.063943560000000e+03 * invT + 1.247806300000001e-01 -
                 3.782456360000000e+00 * logT + 1.498367080000000e-03 * T -
                 1.641217001666667e-06 * T2 + 8.067745908333334e-10 * T3 -
                 1.621864185000000e-13 * T4;
    // species 1: H2O
    species[1] = -3.029372600000000e+04 * invT + 5.047667408000000e+00 -
                 4.198635200000000e+00 * logT + 1.018200850000000e-03 * T -
                 1.086723600000000e-06 * T2 + 4.573272416666666e-10 * T3 -
                 8.859840000000001e-14 * T4;
    // species 2: CH4
    species[2] = -1.024659830000000e+04 * invT + 9.790418440000000e+00 -
                 5.149114680000000e+00 * logT + 6.831100450000000e-03 * T -
                 8.190898683333333e-06 * T2 + 4.035389725000000e-09 * T3 -
                 8.330172050000000e-13 * T4;
    // species 3: CO2
    species[3] = -4.837197100000000e+04 * invT - 7.544239220000001e+00 -
                 2.356813000000000e+00 * logT - 4.492064950000000e-03 * T +
                 1.187010533333333e-06 * T2 - 2.047750666666667e-10 * T3 +
                 7.144273999999999e-15 * T4;
    // species 4: N2
    species[4] = -1.046976280000000e+03 * invT - 4.193667200000002e-01 -
                 3.531005280000000e+00 * logT + 6.183049400000000e-05 * T +
                 8.383323883333334e-08 * T2 - 2.029421766666667e-10 * T3 +
                 7.044061750000001e-14 * T4;
  } else {
    // species 0: O2
    species[0] = -1.215977180000000e+03 * invT - 1.792270640000000e+00 -
                 3.660960650000000e+00 * logT - 3.281829055000000e-04 * T +
                 2.352493783333333e-08 * T2 - 1.714982791666666e-12 * T3 +
                 6.495671800000001e-17 * T4;
    // species 1: H2O
    species[1] = -2.988589400000000e+04 * invT - 2.289731200000000e+00 -
                 2.677038900000000e+00 * logT - 1.486590800000000e-03 * T +
                 1.289614816666667e-07 * T2 - 7.869459500000001e-12 * T3 +
                 2.134499550000000e-16 * T4;
    // species 2: CH4
    species[2] = -1.000959360000000e+04 * invT - 1.678405574000000e+01 -
                 1.653262260000000e+00 * logT - 5.013154950000000e-03 * T +
                 5.527687300000000e-07 * T2 - 4.470692816666667e-11 * T3 +
                 1.573483790000000e-15 * T4;
    // species 3: CO2
    species[3] = -4.902490400000000e+04 * invT + 2.364873040000000e+00 -
                 4.636511100000000e+00 * logT - 1.370728450000000e-03 * T +
                 1.659829316666667e-07 * T2 - 1.336555500000000e-11 * T3 +
                 4.580992850000000e-16 * T4;
    // species 4: N2
    species[4] = -9.239486879999999e+02 * invT - 3.027951630000000e+00 -
                 2.952576370000000e+00 * logT - 6.984502000000001e-04 * T +
                 8.210526716666667e-08 * T2 - 6.550084958333333e-12 * T3 +
                 2.303776020000000e-16 * T4;
  }
}

// compute the a/(RT) at the given temperature
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
helmholtz(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real invT = 1.0 / T;
  const amrex::Real logT = log(T);

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = -1.063943560000000e+03 * invT - 8.752193699999999e-01 -
                 3.782456360000000e+00 * logT + 1.498367080000000e-03 * T -
                 1.641217001666667e-06 * T2 + 8.067745908333334e-10 * T3 -
                 1.621864185000000e-13 * T4;
    // species 1: H2O
    species[1] = -3.029372600000000e+04 * invT + 4.047667408000000e+00 -
                 4.198635200000000e+00 * logT + 1.018200850000000e-03 * T -
                 1.086723600000000e-06 * T2 + 4.573272416666666e-10 * T3 -
                 8.859840000000001e-14 * T4;
    // species 2: CH4
    species[2] = -1.024659830000000e+04 * invT + 8.790418440000000e+00 -
                 5.149114680000000e+00 * logT + 6.831100450000000e-03 * T -
                 8.190898683333333e-06 * T2 + 4.035389725000000e-09 * T3 -
                 8.330172050000000e-13 * T4;
    // species 3: CO2
    species[3] = -4.837197100000000e+04 * invT - 8.544239220000001e+00 -
                 2.356813000000000e+00 * logT - 4.492064950000000e-03 * T +
                 1.187010533333333e-06 * T2 - 2.047750666666667e-10 * T3 +
                 7.144273999999999e-15 * T4;
    // species 4: N2
    species[4] = -1.046976280000000e+03 * invT - 1.419366720000000e+00 -
                 3.531005280000000e+00 * logT + 6.183049400000000e-05 * T +
                 8.383323883333334e-08 * T2 - 2.029421766666667e-10 * T3 +
                 7.044061750000001e-14 * T4;
  } else {
    // species 0: O2
    species[0] = -1.215977180000000e+03 * invT - 2.792270640000000e+00 -
                 3.660960650000000e+00 * logT - 3.281829055000000e-04 * T +
                 2.352493783333333e-08 * T2 - 1.714982791666666e-12 * T3 +
                 6.495671800000001e-17 * T4;
    // species 1: H2O
    species[1] = -2.988589400000000e+04 * invT - 3.289731200000000e+00 -
                 2.677038900000000e+00 * logT - 1.486590800000000e-03 * T +
                 1.289614816666667e-07 * T2 - 7.869459500000001e-12 * T3 +
                 2.134499550000000e-16 * T4;
    // species 2: CH4
    species[2] = -1.000959360000000e+04 * invT - 1.778405574000000e+01 -
                 1.653262260000000e+00 * logT - 5.013154950000000e-03 * T +
                 5.527687300000000e-07 * T2 - 4.470692816666667e-11 * T3 +
                 1.573483790000000e-15 * T4;
    // species 3: CO2
    species[3] = -4.902490400000000e+04 * invT + 1.364873040000000e+00 -
                 4.636511100000000e+00 * logT - 1.370728450000000e-03 * T +
                 1.659829316666667e-07 * T2 - 1.336555500000000e-11 * T3 +
                 4.580992850000000e-16 * T4;
    // species 4: N2
    species[4] = -9.239486879999999e+02 * invT - 4.027951630000000e+00 -
                 2.952576370000000e+00 * logT - 6.984502000000001e-04 * T +
                 8.210526716666667e-08 * T2 - 6.550084958333333e-12 * T3 +
                 2.303776020000000e-16 * T4;
  }
}

// compute the e/(RT) at the given temperature
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
speciesInternalEnergy(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real invT = 1.0 / T;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = +2.782456360000000e+00 - 1.498367080000000e-03 * T +
                 3.282434003333333e-06 * T2 - 2.420323772500000e-09 * T3 +
                 6.487456740000000e-13 * T4 - 1.063943560000000e+03 * invT;
    // species 1: H2O
    species[1] = +3.198635200000000e+00 - 1.018200850000000e-03 * T +
                 2.173447200000000e-06 * T2 - 1.371981725000000e-09 * T3 +
                 3.543936000000000e-13 * T4 - 3.029372600000000e+04 * invT;
    // species 2: CH4
    species[2] = +4.149114680000000e+00 - 6.831100450000000e-03 * T +
                 1.638179736666667e-05 * T2 - 1.210616917500000e-08 * T3 +
                 3.332068820000000e-12 * T4 - 1.024659830000000e+04 * invT;
    // species 3: CO2
    species[3] = +1.356813000000000e+00 + 4.492064950000000e-03 * T -
                 2.374021066666667e-06 * T2 + 6.143252000000000e-10 * T3 -
                 2.857709600000000e-14 * T4 - 4.837197100000000e+04 * invT;
    // species 4: N2
    species[4] = +2.531005280000000e+00 - 6.183049400000000e-05 * T -
                 1.676664776666667e-07 * T2 + 6.088265300000000e-10 * T3 -
                 2.817624700000000e-13 * T4 - 1.046976280000000e+03 * invT;
  } else {
    // species 0: O2
    species[0] = +2.660960650000000e+00 + 3.281829055000000e-04 * T -
                 4.704987566666666e-08 * T2 + 5.144948375000000e-12 * T3 -
                 2.598268720000000e-16 * T4 - 1.215977180000000e+03 * invT;
    // species 1: H2O
    species[1] = +1.677038900000000e+00 + 1.486590800000000e-03 * T -
                 2.579229633333333e-07 * T2 + 2.360837850000000e-11 * T3 -
                 8.537998200000000e-16 * T4 - 2.988589400000000e+04 * invT;
    // species 2: CH4
    species[2] = +6.532622600000000e-01 + 5.013154950000000e-03 * T -
                 1.105537460000000e-06 * T2 + 1.341207845000000e-10 * T3 -
                 6.293935160000000e-15 * T4 - 1.000959360000000e+04 * invT;
    // species 3: CO2
    species[3] = +3.636511100000000e+00 + 1.370728450000000e-03 * T -
                 3.319658633333334e-07 * T2 + 4.009666500000000e-11 * T3 -
                 1.832397140000000e-15 * T4 - 4.902490400000000e+04 * invT;
    // species 4: N2
    species[4] = +1.952576370000000e+00 + 6.984502000000001e-04 * T -
                 1.642105343333333e-07 * T2 + 1.965025487500000e-11 * T3 -
                 9.215104079999999e-16 * T4 - 9.239486879999999e+02 * invT;
  }
}

// compute the h/(RT) at the given temperature (Eq 20)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
speciesEnthalpy(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real invT = 1.0 / T;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = +3.782456360000000e+00 - 1.498367080000000e-03 * T +
                 3.282434003333333e-06 * T2 - 2.420323772500000e-09 * T3 +
                 6.487456740000000e-13 * T4 - 1.063943560000000e+03 * invT;
    // species 1: H2O
    species[1] = +4.198635200000000e+00 - 1.018200850000000e-03 * T +
                 2.173447200000000e-06 * T2 - 1.371981725000000e-09 * T3 +
                 3.543936000000000e-13 * T4 - 3.029372600000000e+04 * invT;
    // species 2: CH4
    species[2] = +5.149114680000000e+00 - 6.831100450000000e-03 * T +
                 1.638179736666667e-05 * T2 - 1.210616917500000e-08 * T3 +
                 3.332068820000000e-12 * T4 - 1.024659830000000e+04 * invT;
    // species 3: CO2
    species[3] = +2.356813000000000e+00 + 4.492064950000000e-03 * T -
                 2.374021066666667e-06 * T2 + 6.143252000000000e-10 * T3 -
                 2.857709600000000e-14 * T4 - 4.837197100000000e+04 * invT;
    // species 4: N2
    species[4] = +3.531005280000000e+00 - 6.183049400000000e-05 * T -
                 1.676664776666667e-07 * T2 + 6.088265300000000e-10 * T3 -
                 2.817624700000000e-13 * T4 - 1.046976280000000e+03 * invT;
  } else {
    // species 0: O2
    species[0] = +3.660960650000000e+00 + 3.281829055000000e-04 * T -
                 4.704987566666666e-08 * T2 + 5.144948375000000e-12 * T3 -
                 2.598268720000000e-16 * T4 - 1.215977180000000e+03 * invT;
    // species 1: H2O
    species[1] = +2.677038900000000e+00 + 1.486590800000000e-03 * T -
                 2.579229633333333e-07 * T2 + 2.360837850000000e-11 * T3 -
                 8.537998200000000e-16 * T4 - 2.988589400000000e+04 * invT;
    // species 2: CH4
    species[2] = +1.653262260000000e+00 + 5.013154950000000e-03 * T -
                 1.105537460000000e-06 * T2 + 1.341207845000000e-10 * T3 -
                 6.293935160000000e-15 * T4 - 1.000959360000000e+04 * invT;
    // species 3: CO2
    species[3] = +4.636511100000000e+00 + 1.370728450000000e-03 * T -
                 3.319658633333334e-07 * T2 + 4.009666500000000e-11 * T3 -
                 1.832397140000000e-15 * T4 - 4.902490400000000e+04 * invT;
    // species 4: N2
    species[4] = +2.952576370000000e+00 + 6.984502000000001e-04 * T -
                 1.642105343333333e-07 * T2 + 1.965025487500000e-11 * T3 -
                 9.215104079999999e-16 * T4 - 9.239486879999999e+02 * invT;
  }
}

// compute the S/R at the given temperature (Eq 21)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
speciesEntropy(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real logT = log(T);

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = +3.782456360000000e+00 * logT - 2.996734160000000e-03 * T +
                 4.923651005000000e-06 * T2 - 3.227098363333333e-09 * T3 +
                 8.109320925000000e-13 * T4 + 3.657675730000000e+00;
    // species 1: H2O
    species[1] = +4.198635200000000e+00 * logT - 2.036401700000000e-03 * T +
                 3.260170800000000e-06 * T2 - 1.829308966666667e-09 * T3 +
                 4.429920000000000e-13 * T4 - 8.490322080000000e-01;
    // species 2: CH4
    species[2] = +5.149114680000000e+00 * logT - 1.366220090000000e-02 * T +
                 2.457269605000000e-05 * T2 - 1.614155890000000e-08 * T3 +
                 4.165086025000000e-12 * T4 - 4.641303760000000e+00;
    // species 3: CO2
    species[3] = +2.356813000000000e+00 * logT + 8.984129900000000e-03 * T -
                 3.561031600000000e-06 * T2 + 8.191002666666667e-10 * T3 -
                 3.572137000000000e-14 * T4 + 9.901052220000000e+00;
    // species 4: N2
    species[4] = +3.531005280000000e+00 * logT - 1.236609880000000e-04 * T -
                 2.514997165000000e-07 * T2 + 8.117687066666667e-10 * T3 -
                 3.522030875000000e-13 * T4 + 3.950372000000000e+00;
  } else {
    // species 0: O2
    species[0] = +3.660960650000000e+00 * logT + 6.563658110000000e-04 * T -
                 7.057481349999999e-08 * T2 + 6.859931166666666e-12 * T3 -
                 3.247835900000000e-16 * T4 + 5.453231290000000e+00;
    // species 1: H2O
    species[1] = +2.677038900000000e+00 * logT + 2.973181600000000e-03 * T -
                 3.868844450000000e-07 * T2 + 3.147783800000000e-11 * T3 -
                 1.067249775000000e-15 * T4 + 4.966770100000000e+00;
    // species 2: CH4
    species[2] = +1.653262260000000e+00 * logT + 1.002630990000000e-02 * T -
                 1.658306190000000e-06 * T2 + 1.788277126666667e-10 * T3 -
                 7.867418950000000e-15 * T4 + 1.843731800000000e+01;
    // species 3: CO2
    species[3] = +4.636511100000000e+00 * logT + 2.741456900000000e-03 * T -
                 4.979487950000000e-07 * T2 + 5.346222000000000e-11 * T3 -
                 2.290496425000000e-15 * T4 + 2.271638060000000e+00;
    // species 4: N2
    species[4] = +2.952576370000000e+00 * logT + 1.396900400000000e-03 * T -
                 2.463158015000000e-07 * T2 + 2.620033983333333e-11 * T3 -
                 1.151888010000000e-15 * T4 + 5.980528000000000e+00;
  }
}

// compute d(Cp/R)/dT and d(Cv/R)/dT at the given temperature
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
dcvpRdT(amrex::Real* species, const amrex::Real T)
{
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    species[0] = -2.996734160000000e-03 + 1.969460402000000e-05 * T -
                 2.904388527000000e-08 * T2 + 1.297491348000000e-11 * T3;
    // species 1: H2O
    species[1] = -2.036401700000000e-03 + 1.304068320000000e-05 * T -
                 1.646378070000000e-08 * T2 + 7.087872000000000e-12 * T3;
    // species 2: CH4
    species[2] = -1.366220090000000e-02 + 9.829078420000000e-05 * T -
                 1.452740301000000e-07 * T2 + 6.664137640000000e-11 * T3;
    // species 3: CO2
    species[3] = +8.984129900000000e-03 - 1.424412640000000e-05 * T +
                 7.371902400000000e-09 * T2 - 5.715419200000000e-13 * T3;
    // species 4: N2
    species[4] = -1.236609880000000e-04 - 1.005998866000000e-06 * T +
                 7.305918360000000e-09 * T2 - 5.635249400000000e-12 * T3;
  } else {
    // species 0: O2
    species[0] = +6.563658110000000e-04 - 2.822992540000000e-07 * T +
                 6.173938050000000e-11 * T2 - 5.196537440000000e-15 * T3;
    // species 1: H2O
    species[1] = +2.973181600000000e-03 - 1.547537780000000e-06 * T +
                 2.833005420000000e-10 * T2 - 1.707599640000000e-14 * T3;
    // species 2: CH4
    species[2] = +1.002630990000000e-02 - 6.633224760000000e-06 * T +
                 1.609449414000000e-09 * T2 - 1.258787032000000e-13 * T3;
    // species 3: CO2
    species[3] = +2.741456900000000e-03 - 1.991795180000000e-06 * T +
                 4.811599800000000e-10 * T2 - 3.664794280000000e-14 * T3;
    // species 4: N2
    species[4] = +1.396900400000000e-03 - 9.852632060000001e-07 * T +
                 2.358030585000000e-10 * T2 - 1.843020816000000e-14 * T3;
  }
}

// Returns the mean specific heat at CP (Eq. 33)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCPBL(const amrex::Real T, const amrex::Real x[], amrex::Real& cpbl)
{
  amrex::Real result = 0;
  amrex::Real cpor[5]; //  temporary storage
  cp_R(cpor, T);

  // perform dot product
  for (int id = 0; id < 5; ++id) {
    result += x[id] * cpor[id];
  }

  cpbl = result * 8.31446261815324e+07;
}

// Returns the mean specific heat at CP (Eq. 34)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCPBS(const amrex::Real T, const amrex::Real y[], amrex::Real& cpbs)
{
  amrex::Real result = 0.0;

  // compute Cp/R at the given temperature
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    result += y[0] *
              (+3.782456360000000e+00 - 2.996734160000000e-03 * T +
               9.847302010000000e-06 * T2 - 9.681295090000001e-09 * T3 +
               3.243728370000000e-12 * T4) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+4.198635200000000e+00 - 2.036401700000000e-03 * T +
               6.520341600000000e-06 * T2 - 5.487926900000000e-09 * T3 +
               1.771968000000000e-12 * T4) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+5.149114680000000e+00 - 1.366220090000000e-02 * T +
               4.914539210000000e-05 * T2 - 4.842467670000000e-08 * T3 +
               1.666034410000000e-11 * T4) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+2.356813000000000e+00 + 8.984129900000000e-03 * T -
               7.122063200000000e-06 * T2 + 2.457300800000000e-09 * T3 -
               1.428854800000000e-13 * T4) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+3.531005280000000e+00 - 1.236609880000000e-04 * T -
               5.029994330000001e-07 * T2 + 2.435306120000000e-09 * T3 -
               1.408812350000000e-12 * T4) *
              0.0356964374955379;
  } else {
    // species 0: O2
    result += y[0] *
              (+3.660960650000000e+00 + 6.563658110000000e-04 * T -
               1.411496270000000e-07 * T2 + 2.057979350000000e-11 * T3 -
               1.299134360000000e-15 * T4) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+2.677038900000000e+00 + 2.973181600000000e-03 * T -
               7.737688900000000e-07 * T2 + 9.443351400000000e-11 * T3 -
               4.268999100000000e-15 * T4) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+1.653262260000000e+00 + 1.002630990000000e-02 * T -
               3.316612380000000e-06 * T2 + 5.364831380000000e-10 * T3 -
               3.146967580000000e-14 * T4) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+4.636511100000000e+00 + 2.741456900000000e-03 * T -
               9.958975900000000e-07 * T2 + 1.603866600000000e-10 * T3 -
               9.161985700000000e-15 * T4) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+2.952576370000000e+00 + 1.396900400000000e-03 * T -
               4.926316030000000e-07 * T2 + 7.860101950000000e-11 * T3 -
               4.607552040000000e-15 * T4) *
              0.0356964374955379;
  }

  cpbs = result * 8.31446261815324e+07;
}

// Returns the mean specific heat at CV (Eq. 35)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCVBL(const amrex::Real T, const amrex::Real x[], amrex::Real& cvbl)
{
  amrex::Real result = 0;
  amrex::Real cvor[5]; //  temporary storage
  cv_R(cvor, T);

  // perform dot product
  for (int id = 0; id < 5; ++id) {
    result += x[id] * cvor[id];
  }

  cvbl = result * 8.31446261815324e+07;
}

// Returns the mean specific heat at CV (Eq. 36)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCVBS(const amrex::Real T, const amrex::Real y[], amrex::Real& cvbs)
{
  amrex::Real result = 0.0;
  // compute Cv/R at the given temperature
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    result += y[0] *
              (+2.782456360000000e+00 - 2.996734160000000e-03 * T +
               9.847302010000000e-06 * T2 - 9.681295090000001e-09 * T3 +
               3.243728370000000e-12 * T4) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+3.198635200000000e+00 - 2.036401700000000e-03 * T +
               6.520341600000000e-06 * T2 - 5.487926900000000e-09 * T3 +
               1.771968000000000e-12 * T4) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+4.149114680000000e+00 - 1.366220090000000e-02 * T +
               4.914539210000000e-05 * T2 - 4.842467670000000e-08 * T3 +
               1.666034410000000e-11 * T4) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+1.356813000000000e+00 + 8.984129900000000e-03 * T -
               7.122063200000000e-06 * T2 + 2.457300800000000e-09 * T3 -
               1.428854800000000e-13 * T4) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+2.531005280000000e+00 - 1.236609880000000e-04 * T -
               5.029994330000001e-07 * T2 + 2.435306120000000e-09 * T3 -
               1.408812350000000e-12 * T4) *
              0.0356964374955379;
  } else {
    // species 0: O2
    result += y[0] *
              (+2.660960650000000e+00 + 6.563658110000000e-04 * T -
               1.411496270000000e-07 * T2 + 2.057979350000000e-11 * T3 -
               1.299134360000000e-15 * T4) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+1.677038900000000e+00 + 2.973181600000000e-03 * T -
               7.737688900000000e-07 * T2 + 9.443351400000000e-11 * T3 -
               4.268999100000000e-15 * T4) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+6.532622600000000e-01 + 1.002630990000000e-02 * T -
               3.316612380000000e-06 * T2 + 5.364831380000000e-10 * T3 -
               3.146967580000000e-14 * T4) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+3.636511100000000e+00 + 2.741456900000000e-03 * T -
               9.958975900000000e-07 * T2 + 1.603866600000000e-10 * T3 -
               9.161985700000000e-15 * T4) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+1.952576370000000e+00 + 1.396900400000000e-03 * T -
               4.926316030000000e-07 * T2 + 7.860101950000000e-11 * T3 -
               4.607552040000000e-15 * T4) *
              0.0356964374955379;
  }

  cvbs = result * 8.31446261815324e+07;
}

// Returns the mean enthalpy of the mixture in molar units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKHBML(const amrex::Real T, const amrex::Real x[], amrex::Real& hbml)
{
  amrex::Real result = 0;
  amrex::Real hml[5];                        //  temporary storage
  amrex::Real RT = 8.31446261815324e+07 * T; // R*T
  speciesEnthalpy(hml, T);

  // perform dot product
  for (int id = 0; id < 5; ++id) {
    result += x[id] * hml[id];
  }

  hbml = result * RT;
}

// Returns mean enthalpy of mixture in mass units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKHBMS(const amrex::Real T, const amrex::Real y[], amrex::Real& hbms)
{
  amrex::Real result = 0.0;
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real invT = 1.0 / T;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    result += y[0] *
              (+3.782456360000000e+00 - 1.498367080000000e-03 * T +
               3.282434003333333e-06 * T2 - 2.420323772500000e-09 * T3 +
               6.487456740000000e-13 * T4 - 1.063943560000000e+03 * invT) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+4.198635200000000e+00 - 1.018200850000000e-03 * T +
               2.173447200000000e-06 * T2 - 1.371981725000000e-09 * T3 +
               3.543936000000000e-13 * T4 - 3.029372600000000e+04 * invT) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+5.149114680000000e+00 - 6.831100450000000e-03 * T +
               1.638179736666667e-05 * T2 - 1.210616917500000e-08 * T3 +
               3.332068820000000e-12 * T4 - 1.024659830000000e+04 * invT) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+2.356813000000000e+00 + 4.492064950000000e-03 * T -
               2.374021066666667e-06 * T2 + 6.143252000000000e-10 * T3 -
               2.857709600000000e-14 * T4 - 4.837197100000000e+04 * invT) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+3.531005280000000e+00 - 6.183049400000000e-05 * T -
               1.676664776666667e-07 * T2 + 6.088265300000000e-10 * T3 -
               2.817624700000000e-13 * T4 - 1.046976280000000e+03 * invT) *
              0.0356964374955379;
  } else {
    // species 0: O2
    result += y[0] *
              (+3.660960650000000e+00 + 3.281829055000000e-04 * T -
               4.704987566666666e-08 * T2 + 5.144948375000000e-12 * T3 -
               2.598268720000000e-16 * T4 - 1.215977180000000e+03 * invT) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+2.677038900000000e+00 + 1.486590800000000e-03 * T -
               2.579229633333333e-07 * T2 + 2.360837850000000e-11 * T3 -
               8.537998200000000e-16 * T4 - 2.988589400000000e+04 * invT) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+1.653262260000000e+00 + 5.013154950000000e-03 * T -
               1.105537460000000e-06 * T2 + 1.341207845000000e-10 * T3 -
               6.293935160000000e-15 * T4 - 1.000959360000000e+04 * invT) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+4.636511100000000e+00 + 1.370728450000000e-03 * T -
               3.319658633333334e-07 * T2 + 4.009666500000000e-11 * T3 -
               1.832397140000000e-15 * T4 - 4.902490400000000e+04 * invT) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+2.952576370000000e+00 + 6.984502000000001e-04 * T -
               1.642105343333333e-07 * T2 + 1.965025487500000e-11 * T3 -
               9.215104079999999e-16 * T4 - 9.239486879999999e+02 * invT) *
              0.0356964374955379;
  }

  const amrex::Real RT = 8.31446261815324e+07 * T; // R*T

  hbms = result * RT;
}

// get mean internal energy in molar units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKUBML(const amrex::Real T, const amrex::Real x[], amrex::Real& ubml)
{
  amrex::Real result = 0;
  amrex::Real uml[5];                        //  temporary energy array
  amrex::Real RT = 8.31446261815324e+07 * T; // R*T
  speciesInternalEnergy(uml, T);

  // perform dot product
  for (int id = 0; id < 5; ++id) {
    result += x[id] * uml[id];
  }

  ubml = result * RT;
}

// get mean internal energy in mass units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKUBMS(const amrex::Real T, const amrex::Real y[], amrex::Real& ubms)
{
  amrex::Real result = 0.0;
  const amrex::Real T2 = T * T;
  const amrex::Real T3 = T * T2;
  const amrex::Real T4 = T * T3;
  const amrex::Real invT = 1.0 / T;

  // species with midpoint at T=1000 kelvin
  if (T < 1000) {
    // species 0: O2
    result += y[0] *
              (+2.782456360000000e+00 - 1.498367080000000e-03 * T +
               3.282434003333333e-06 * T2 - 2.420323772500000e-09 * T3 +
               6.487456740000000e-13 * T4 - 1.063943560000000e+03 * invT) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+3.198635200000000e+00 - 1.018200850000000e-03 * T +
               2.173447200000000e-06 * T2 - 1.371981725000000e-09 * T3 +
               3.543936000000000e-13 * T4 - 3.029372600000000e+04 * invT) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+4.149114680000000e+00 - 6.831100450000000e-03 * T +
               1.638179736666667e-05 * T2 - 1.210616917500000e-08 * T3 +
               3.332068820000000e-12 * T4 - 1.024659830000000e+04 * invT) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+1.356813000000000e+00 + 4.492064950000000e-03 * T -
               2.374021066666667e-06 * T2 + 6.143252000000000e-10 * T3 -
               2.857709600000000e-14 * T4 - 4.837197100000000e+04 * invT) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+2.531005280000000e+00 - 6.183049400000000e-05 * T -
               1.676664776666667e-07 * T2 + 6.088265300000000e-10 * T3 -
               2.817624700000000e-13 * T4 - 1.046976280000000e+03 * invT) *
              0.0356964374955379;
  } else {
    // species 0: O2
    result += y[0] *
              (+2.660960650000000e+00 + 3.281829055000000e-04 * T -
               4.704987566666666e-08 * T2 + 5.144948375000000e-12 * T3 -
               2.598268720000000e-16 * T4 - 1.215977180000000e+03 * invT) *
              0.0312519532470779;
    // species 1: H2O
    result += y[1] *
              (+1.677038900000000e+00 + 1.486590800000000e-03 * T -
               2.579229633333333e-07 * T2 + 2.360837850000000e-11 * T3 -
               8.537998200000000e-16 * T4 - 2.988589400000000e+04 * invT) *
              0.0555092978073827;
    // species 2: CH4
    result += y[2] *
              (+6.532622600000000e-01 + 5.013154950000000e-03 * T -
               1.105537460000000e-06 * T2 + 1.341207845000000e-10 * T3 -
               6.293935160000000e-15 * T4 - 1.000959360000000e+04 * invT) *
              0.0623324814560868;
    // species 3: CO2
    result += y[3] *
              (+3.636511100000000e+00 + 1.370728450000000e-03 * T -
               3.319658633333334e-07 * T2 + 4.009666500000000e-11 * T3 -
               1.832397140000000e-15 * T4 - 4.902490400000000e+04 * invT) *
              0.0227226249176305;
    // species 4: N2
    result += y[4] *
              (+1.952576370000000e+00 + 6.984502000000001e-04 * T -
               1.642105343333333e-07 * T2 + 1.965025487500000e-11 * T3 -
               9.215104079999999e-16 * T4 - 9.239486879999999e+02 * invT) *
              0.0356964374955379;
  }

  const amrex::Real RT = 8.31446261815324e+07 * T; // R*T

  ubms = result * RT;
}

// get mixture entropy in molar units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKSBML(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real x[],
  amrex::Real& sbml)
{
  amrex::Real result = 0;
  // Log of normalized pressure in cgs units dynes/cm^2 by Patm
  amrex::Real logPratio = log(P / 1013250.0);
  amrex::Real sor[5]; //  temporary storage
  speciesEntropy(sor, T);

  // Compute Eq 42
  for (int id = 0; id < 5; ++id) {
    result += x[id] * (sor[id] - log((x[id] + 1e-100)) - logPratio);
  }

  sbml = result * 8.31446261815324e+07;
}

// get mixture entropy in mass units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKSBMS(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real y[],
  amrex::Real& sbms)
{
  amrex::Real result = 0;
  // Log of normalized pressure in cgs units dynes/cm^2 by Patm
  amrex::Real logPratio = log(P / 1013250.0);
  amrex::Real sor[5];  //  temporary storage
  amrex::Real x[5];    //  need a ytx conversion
  amrex::Real YOW = 0; // See Eq 4, 6 in CK Manual

  // Compute inverse of mean molecular wt first
  for (int i = 0; i < 5; i++) {
    YOW += y[i] * imw(i);
  }
  // Now compute y to x conversion
  x[0] = y[0] / (3.1998000000000001e+01 * YOW);
  x[1] = y[1] / (1.8015000000000001e+01 * YOW);
  x[2] = y[2] / (1.6042999999999999e+01 * YOW);
  x[3] = y[3] / (4.4009000000000000e+01 * YOW);
  x[4] = y[4] / (2.8013999999999999e+01 * YOW);
  speciesEntropy(sor, T);
  // Perform computation in Eq 42 and 43
  for (int i = 0; i < 5; i++) {
    result += x[i] * (sor[i] - log((x[i] + 1e-100)) - logPratio);
  }
  // Scale by R/W
  sbms = result * 8.31446261815324e+07 * YOW;
}

//  get temperature given internal energy in mass units and mass fracs
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
GET_T_GIVEN_EY(
  const amrex::Real e, const amrex::Real y[], amrex::Real& t, int& ierr)
{
#ifdef CONVERGENCE
  const int maxiter = 5000;
  const amrex::Real tol = 1.e-12;
#else
  const int maxiter = 200;
  const amrex::Real tol = 1.e-6;
#endif
  amrex::Real tmin = 200.0;  // max lower bound for thermo def
  amrex::Real tmax = 3500.0; // min upper bound for thermo def
  amrex::Real e1, emin, emax, cv, t1, dt;
  CKUBMS(tmin, y, emin);
  CKUBMS(tmax, y, emax);
  if (e < emin) {
    // Linear Extrapolation below tmin
    CKCVBS(tmin, y, cv);
    t = tmin - (emin - e) / cv;
    ierr = 1;
    return;
  }
  if (e > emax) {
    // Linear Extrapolation above tmax
    CKCVBS(tmax, y, cv);
    t = tmax - (emax - e) / cv;
    ierr = 1;
    return;
  }
  t1 = t;
  if (t1 < tmin || t1 > tmax) {
    t1 = tmin + (tmax - tmin) / (emax - emin) * (e - emin);
  }
  for (int i = 0; i < maxiter; ++i) {
    CKUBMS(t1, y, e1);
    CKCVBS(t1, y, cv);
    dt = (e - e1) / cv;
    if (dt > 100.) {
      dt = 100.;
    } else if (dt < -100.) {
      dt = -100.;
    } else if (fabs(dt) < tol) {
      break;
    }
    t1 += dt;
  }
  t = t1;
  ierr = 0;
}

//  get temperature given enthalpy in mass units and mass fracs
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
GET_T_GIVEN_HY(
  const amrex::Real h, const amrex::Real y[], amrex::Real& t, int& ierr)
{
#ifdef CONVERGENCE
  const int maxiter = 5000;
  const amrex::Real tol = 1.e-12;
#else
  const int maxiter = 200;
  const amrex::Real tol = 1.e-6;
#endif
  amrex::Real tmin = 200.0;  // max lower bound for thermo def
  amrex::Real tmax = 3500.0; // min upper bound for thermo def
  amrex::Real h1, hmin, hmax, cp, t1, dt;
  CKHBMS(tmin, y, hmin);
  CKHBMS(tmax, y, hmax);
  if (h < hmin) {
    // Linear Extrapolation below tmin
    CKCPBS(tmin, y, cp);
    t = tmin - (hmin - h) / cp;
    ierr = 1;
    return;
  }
  if (h > hmax) {
    // Linear Extrapolation above tmax
    CKCPBS(tmax, y, cp);
    t = tmax - (hmax - h) / cp;
    ierr = 1;
    return;
  }
  t1 = t;
  if (t1 < tmin || t1 > tmax) {
    t1 = tmin + (tmax - tmin) / (hmax - hmin) * (h - hmin);
  }
  for (int i = 0; i < maxiter; ++i) {
    CKHBMS(t1, y, h1);
    CKCPBS(t1, y, cp);
    dt = (h - h1) / cp;
    if (dt > 100.) {
      dt = 100.;
    } else if (dt < -100.) {
      dt = -100.;
    } else if (fabs(dt) < tol) {
      break;
    }
    t1 += dt;
  }
  t = t1;
  ierr = 0;
}

// Compute P = rhoRT/W(x)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKPX(
  const amrex::Real rho,
  const amrex::Real T,
  const amrex::Real x[],
  amrex::Real& P)
{
  amrex::Real XW = 0;                      //  To hold mean molecular wt
  XW += x[0] * 3.1998000000000001e+01;     // O2
  XW += x[1] * 1.8015000000000001e+01;     // H2O
  XW += x[2] * 1.6042999999999999e+01;     // CH4
  XW += x[3] * 4.4009000000000000e+01;     // CO2
  XW += x[4] * 2.8013999999999999e+01;     // N2
  P = rho * 8.31446261815324e+07 * T / XW; // P = rho*R*T/W
}

// Compute P = rhoRT/W(y)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKPY(
  const amrex::Real rho,
  const amrex::Real T,
  const amrex::Real y[],
  amrex::Real& P)
{
  amrex::Real YOW = 0; //  for computing mean MW

  for (int i = 0; i < 5; i++) {
    YOW += y[i] * imw(i);
  }
  P = rho * 8.31446261815324e+07 * T * YOW; // P = rho*R*T/W
}

// Compute P = rhoRT/W(c)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKPC(
  const amrex::Real rho,
  const amrex::Real T,
  const amrex::Real c[],
  amrex::Real& P)
{
  // See Eq 5 in CK Manual
  amrex::Real W = 0;
  amrex::Real sumC = 0;
  W += c[0] * 3.1998000000000001e+01; // O2
  W += c[1] * 1.8015000000000001e+01; // H2O
  W += c[2] * 1.6042999999999999e+01; // CH4
  W += c[3] * 4.4009000000000000e+01; // CO2
  W += c[4] * 2.8013999999999999e+01; // N2

  for (int id = 0; id < 5; ++id) {
    sumC += c[id];
  }
  P = rho * 8.31446261815324e+07 * T * sumC / W; // P = rho*R*T/W
}

// Compute rho = PW(x)/RT
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKRHOX(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real x[],
  amrex::Real& rho)
{
  amrex::Real XW = 0;                        //  To hold mean molecular wt
  XW += x[0] * 3.1998000000000001e+01;       // O2
  XW += x[1] * 1.8015000000000001e+01;       // H2O
  XW += x[2] * 1.6042999999999999e+01;       // CH4
  XW += x[3] * 4.4009000000000000e+01;       // CO2
  XW += x[4] * 2.8013999999999999e+01;       // N2
  rho = P * XW / (8.31446261815324e+07 * T); // rho = P*W/(R*T)
}

// Compute rho = P*W(y)/RT
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKRHOY(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real y[],
  amrex::Real& rho)
{
  amrex::Real YOW = 0;

  for (int i = 0; i < 5; i++) {
    YOW += y[i] * imw(i);
  }

  rho = P / (8.31446261815324e+07 * T * YOW); // rho = P*W/(R*T)
}

// Compute rho = P*W(c)/(R*T)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKRHOC(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real c[],
  amrex::Real& rho)
{
  // See Eq 5 in CK Manual
  amrex::Real W = 0;
  amrex::Real sumC = 0;
  W += c[0] * 3.1998000000000001e+01; // O2
  W += c[1] * 1.8015000000000001e+01; // H2O
  W += c[2] * 1.6042999999999999e+01; // CH4
  W += c[3] * 4.4009000000000000e+01; // CO2
  W += c[4] * 2.8013999999999999e+01; // N2

  for (int id = 0; id < 5; ++id) {
    sumC += c[id];
  }
  rho = P * W / (sumC * T * 8.31446261815324e+07); // rho = PW/(R*T)
}

// get molecular weight for all species
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKWT(amrex::Real wt[])
{
  get_mw(wt);
}

// given y[species]: mass fractions
// s mean molecular weight (gm/mole)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKMMWY(const amrex::Real y[], amrex::Real& wtm)
{
  amrex::Real YOW = 0;

  for (int i = 0; i < 5; i++) {
    YOW += y[i] * imw(i);
  }

  wtm = 1.0 / YOW;
}

// given x[species]: mole fractions
// returns mean molecular weight (gm/mole)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKMMWX(const amrex::Real x[], amrex::Real& wtm)
{
  amrex::Real XW = 0;                  //  see Eq 4 in CK Manual
  XW += x[0] * 3.1998000000000001e+01; // O2
  XW += x[1] * 1.8015000000000001e+01; // H2O
  XW += x[2] * 1.6042999999999999e+01; // CH4
  XW += x[3] * 4.4009000000000000e+01; // CO2
  XW += x[4] * 2.8013999999999999e+01; // N2
  wtm = XW;
}

// given c[species]: molar concentration
// returns mean molecular weight (gm/mole)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKMMWC(const amrex::Real c[], amrex::Real& wtm)
{
  // See Eq 5 in CK Manual
  amrex::Real W = 0;
  amrex::Real sumC = 0;
  W += c[0] * 3.1998000000000001e+01; // O2
  W += c[1] * 1.8015000000000001e+01; // H2O
  W += c[2] * 1.6042999999999999e+01; // CH4
  W += c[3] * 4.4009000000000000e+01; // CO2
  W += c[4] * 2.8013999999999999e+01; // N2

  for (int id = 0; id < 5; ++id) {
    sumC += c[id];
  }
  //  CK provides no guard against division by zero
  wtm = W / sumC;
}

// get Cp/R as a function of T
// for all species (Eq 19)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCPOR(const amrex::Real T, amrex::Real cpor[])
{
  cp_R(cpor, T);
}

// get H/RT as a function of T
// for all species (Eq 20)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKHORT(const amrex::Real T, amrex::Real hort[])
{
  speciesEnthalpy(hort, T);
}

// get S/R as a function of T
// for all species (Eq 21)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKSOR(const amrex::Real T, amrex::Real sor[])
{
  speciesEntropy(sor, T);
}

// convert y[species] (mass fracs) to x[species] (mole fracs)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKYTX(const amrex::Real y[], amrex::Real x[])
{
  amrex::Real YOW = 0;

  for (int i = 0; i < 5; i++) {
    YOW += y[i] * imw(i);
  }

  amrex::Real YOWINV = 1.0 / YOW;

  for (int i = 0; i < 5; i++) {
    x[i] = y[i] * imw(i) * YOWINV;
  }
}

// convert y[species] (mass fracs) to c[species] (molar conc)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKYTCP(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real y[],
  amrex::Real c[])
{
  amrex::Real YOW = 0;
  amrex::Real PWORT;

  // Compute inverse of mean molecular wt first
  for (int i = 0; i < 5; i++) {
    c[i] = y[i] * imw(i);
  }
  for (int i = 0; i < 5; i++) {
    YOW += c[i];
  }

  // PW/RT (see Eq. 7)
  PWORT = P / (YOW * 8.31446261815324e+07 * T);
  // Now compute conversion

  for (int i = 0; i < 5; i++) {
    c[i] = PWORT * y[i] * imw(i);
  }
}

// convert y[species] (mass fracs) to c[species] (molar conc)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKYTCR(
  const amrex::Real rho,
  amrex::Real /*T*/,
  const amrex::Real y[],
  amrex::Real c[])
{

  for (int i = 0; i < 5; i++) {
    c[i] = rho * y[i] * imw(i);
  }
}

// convert x[species] (mole fracs) to y[species] (mass fracs)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKXTY(const amrex::Real x[], amrex::Real y[])
{
  amrex::Real XW = 0; // See Eq 4, 9 in CK Manual
  // Compute mean molecular wt first
  XW += x[0] * 3.1998000000000001e+01; // O2
  XW += x[1] * 1.8015000000000001e+01; // H2O
  XW += x[2] * 1.6042999999999999e+01; // CH4
  XW += x[3] * 4.4009000000000000e+01; // CO2
  XW += x[4] * 2.8013999999999999e+01; // N2
  // Now compute conversion
  amrex::Real XWinv = 1.0 / XW;
  y[0] = x[0] * 3.1998000000000001e+01 * XWinv;
  y[1] = x[1] * 1.8015000000000001e+01 * XWinv;
  y[2] = x[2] * 1.6042999999999999e+01 * XWinv;
  y[3] = x[3] * 4.4009000000000000e+01 * XWinv;
  y[4] = x[4] * 2.8013999999999999e+01 * XWinv;
}

// convert x[species] (mole fracs) to c[species] (molar conc)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKXTCP(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real x[],
  amrex::Real c[])
{
  amrex::Real PORT = P / (8.31446261815324e+07 * T); // P/RT

  // Compute conversion, see Eq 10
  for (int id = 0; id < 5; ++id) {
    c[id] = x[id] * PORT;
  }
}

// convert x[species] (mole fracs) to c[species] (molar conc)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKXTCR(
  const amrex::Real rho,
  const amrex::Real /*T*/,
  const amrex::Real x[],
  amrex::Real c[])
{
  amrex::Real XW = 0; // See Eq 4, 11 in CK Manual
  amrex::Real ROW;
  // Compute mean molecular wt first
  XW += x[0] * 3.1998000000000001e+01; // O2
  XW += x[1] * 1.8015000000000001e+01; // H2O
  XW += x[2] * 1.6042999999999999e+01; // CH4
  XW += x[3] * 4.4009000000000000e+01; // CO2
  XW += x[4] * 2.8013999999999999e+01; // N2
  ROW = rho / XW;

  // Compute conversion, see Eq 11
  for (int id = 0; id < 5; ++id) {
    c[id] = x[id] * ROW;
  }
}

// convert c[species] (molar conc) to x[species] (mole fracs)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCTX(const amrex::Real c[], amrex::Real x[])
{
  amrex::Real sumC = 0;

  // compute sum of c
  for (int id = 0; id < 5; ++id) {
    sumC += c[id];
  }

  //  See Eq 13
  amrex::Real sumCinv = 1.0 / sumC;
  for (int id = 0; id < 5; ++id) {
    x[id] = c[id] * sumCinv;
  }
}

// convert c[species] (molar conc) to y[species] (mass fracs)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCTY(const amrex::Real c[], amrex::Real y[])
{
  amrex::Real CW = 0; // See Eq 12 in CK Manual
  // compute denominator in eq 12 first
  CW += c[0] * 3.1998000000000001e+01; // O2
  CW += c[1] * 1.8015000000000001e+01; // H2O
  CW += c[2] * 1.6042999999999999e+01; // CH4
  CW += c[3] * 4.4009000000000000e+01; // CO2
  CW += c[4] * 2.8013999999999999e+01; // N2
  // Now compute conversion
  amrex::Real CWinv = 1.0 / CW;
  y[0] = c[0] * 3.1998000000000001e+01 * CWinv;
  y[1] = c[1] * 1.8015000000000001e+01 * CWinv;
  y[2] = c[2] * 1.6042999999999999e+01 * CWinv;
  y[3] = c[3] * 4.4009000000000000e+01 * CWinv;
  y[4] = c[4] * 2.8013999999999999e+01 * CWinv;
}

// get specific heat at constant volume as a function
// of T for all species (molar units)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCVML(const amrex::Real T, amrex::Real cvml[])
{
  cv_R(cvml, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    cvml[id] *= 8.31446261815324e+07;
  }
}

// get specific heat at constant pressure as a
// function of T for all species (molar units)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCPML(const amrex::Real T, amrex::Real cpml[])
{
  cp_R(cpml, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    cpml[id] *= 8.31446261815324e+07;
  }
}

// get internal energy as a function
// of T for all species (molar units)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKUML(const amrex::Real T, amrex::Real uml[])
{
  amrex::Real RT = 8.31446261815324e+07 * T; // R*T
  speciesInternalEnergy(uml, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    uml[id] *= RT;
  }
}

// get enthalpy as a function
// of T for all species (molar units)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKHML(const amrex::Real T, amrex::Real hml[])
{
  amrex::Real RT = 8.31446261815324e+07 * T; // R*T
  speciesEnthalpy(hml, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    hml[id] *= RT;
  }
}

// Returns the standard-state entropies in molar units
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKSML(const amrex::Real T, amrex::Real sml[])
{
  speciesEntropy(sml, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    sml[id] *= 8.31446261815324e+07;
  }
}

// Returns the specific heats at constant volume
// in mass units (Eq. 29)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCVMS(const amrex::Real T, amrex::Real cvms[])
{
  cv_R(cvms, T);
  // multiply by R/molecularweight
  cvms[0] *= 2.598431970171023e+06; // O2
  cvms[1] *= 4.615299815794193e+06; // H2O
  cvms[2] *= 5.182610869633635e+06; // CH4
  cvms[3] *= 1.889264154639560e+06; // CO2
  cvms[4] *= 2.967966951578939e+06; // N2
}

// Returns the specific heats at constant pressure
// in mass units (Eq. 26)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCPMS(const amrex::Real T, amrex::Real cpms[])
{
  cp_R(cpms, T);
  // multiply by R/molecularweight
  cpms[0] *= 2.598431970171023e+06; // O2
  cpms[1] *= 4.615299815794193e+06; // H2O
  cpms[2] *= 5.182610869633635e+06; // CH4
  cpms[3] *= 1.889264154639560e+06; // CO2
  cpms[4] *= 2.967966951578939e+06; // N2
}

// Returns internal energy in mass units (Eq 30.)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKUMS(const amrex::Real T, amrex::Real ums[])
{
  amrex::Real RT = 8.31446261815324e+07 * T; // R*T

  speciesInternalEnergy(ums, T);

  for (int i = 0; i < 5; i++) {
    ums[i] *= RT * imw(i);
  }
}

// Returns enthalpy in mass units (Eq 27.)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKHMS(const amrex::Real T, amrex::Real hms[])
{
  amrex::Real RT = 8.31446261815324e+07 * T; // R*T

  speciesEnthalpy(hms, T);

  for (int i = 0; i < 5; i++) {
    hms[i] *= RT * imw(i);
  }
}

// Returns the entropies in mass units (Eq 28.)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKSMS(const amrex::Real T, amrex::Real sms[])
{
  speciesEntropy(sms, T);
  // multiply by R/molecularweight
  sms[0] *= 2.598431970171023e+06; // O2
  sms[1] *= 4.615299815794193e+06; // H2O
  sms[2] *= 5.182610869633635e+06; // CH4
  sms[3] *= 1.889264154639560e+06; // CO2
  sms[4] *= 2.967966951578939e+06; // N2
}

// GPU version of productionRate: no more use of thermo namespace vectors
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
comp_qfqr(
  amrex::Real* qf,
  amrex::Real* qr,
  const amrex::Real* sc,
  const amrex::Real* /*sc_qss*/,
  const amrex::Real T,
  const amrex::Real invT,
  const amrex::Real logT)
{

  // reaction 0: CH4 + 2 O2 => CO2 + 2 H2O
  qf[0] = sc[0] * sc[2];
  qr[0] = 0.0;

  // compute the mixture concentration
  amrex::Real mixture = 0.0;
  for (int i = 0; i < 5; ++i) {
    mixture += sc[i];
  }

  // compute the Gibbs free energy
  amrex::Real g_RT[5];
  gibbs(g_RT, T);

  // reference concentration: P_atm / (RT) in inverse mol/m^3
  amrex::Real refC = 101325 / 8.31446 * invT;
  amrex::Real refCinv = 1 / refC;

  // Evaluate the kfs
  amrex::Real k_f, Corr;

  // reaction 0:  CH4 + 2 O2 => CO2 + 2 H2O
  k_f = 1000;
  qf[0] *= k_f;
  qr[0] *=
    k_f * exp(-(2.000000 * g_RT[0] - 2.000000 * g_RT[1] + g_RT[2] - g_RT[3]));
}

AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
productionRate(amrex::Real* wdot, const amrex::Real* sc, const amrex::Real T)
{
  const amrex::Real invT = 1.0 / T;
  const amrex::Real logT = log(T);

  // reference concentration: P_atm / (RT) in inverse mol/m^3
  const amrex::Real refC = 101325 / 8.31446 * invT;
  const amrex::Real refCinv = 1 / refC;

  for (int i = 0; i < 5; ++i) {
    wdot[i] = 0.0;
  }

  // compute the mixture concentration
  amrex::Real mixture = 0.0;
  for (int i = 0; i < 5; ++i) {
    mixture += sc[i];
  }

  // compute the Gibbs free energy
  amrex::Real g_RT[5];
  gibbs(g_RT, T);

  {
    // reaction 0:  CH4 + 2 O2 => CO2 + 2 H2O
    const amrex::Real k_f = 1000;
    const amrex::Real qf = k_f * (sc[0] * sc[2]);
    const amrex::Real qr = 0.0;
    const amrex::Real qdot = qf - qr;
    wdot[0] -= 2.000000 * qdot;
    wdot[1] += 2.000000 * qdot;
    wdot[2] -= qdot;
    wdot[3] += qdot;
  }
}

// compute the production rate for each species
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKWC(const amrex::Real T, amrex::Real C[], amrex::Real wdot[])
{

  // convert to SI
  for (int id = 0; id < 5; ++id) {
    C[id] *= 1.0e6;
  }

  // convert to chemkin units
  productionRate(wdot, C, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    C[id] *= 1.0e-6;
    wdot[id] *= 1.0e-6;
  }
}

// Returns the molar production rate of species
// Given P, T, and mass fractions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKWYP(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real y[],
  amrex::Real wdot[])
{
  amrex::Real c[5]; // temporary storage
  amrex::Real YOW = 0;
  amrex::Real PWORT;

  // Compute inverse of mean molecular wt first
  for (int i = 0; i < 5; i++) {
    YOW += y[i] * imw(i);
  }
  // PW/RT (see Eq. 7)
  PWORT = P / (YOW * 8.31446261815324e+07 * T);
  // multiply by 1e6 so c goes to SI
  PWORT *= 1e6;
  // Now compute conversion (and go to SI)
  for (int i = 0; i < 5; i++) {
    c[i] = PWORT * y[i] * imw(i);
  }

  // convert to chemkin units
  productionRate(wdot, c, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    wdot[id] *= 1.0e-6;
  }
}

// Returns the molar production rate of species
// Given P, T, and mole fractions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKWXP(
  const amrex::Real P,
  const amrex::Real T,
  const amrex::Real x[],
  amrex::Real wdot[])
{
  amrex::Real c[5]; // temporary storage
  amrex::Real PORT =
    1e6 * P / (8.31446261815324e+07 * T); // 1e6 * P/RT so c goes to SI units

  // Compute conversion, see Eq 10
  for (int id = 0; id < 5; ++id) {
    c[id] = x[id] * PORT;
  }

  // convert to chemkin units
  productionRate(wdot, c, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    wdot[id] *= 1.0e-6;
  }
}

// Returns the molar production rate of species
// Given rho, T, and mass fractions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKWYR(
  const amrex::Real rho,
  const amrex::Real T,
  const amrex::Real y[],
  amrex::Real wdot[])
{
  amrex::Real c[5]; // temporary storage

  // See Eq 8 with an extra 1e6 so c goes to SI
  for (int i = 0; i < 5; i++) {
    c[i] = 1e6 * rho * y[i] * imw(i);
  }

  // call productionRate
  productionRate(wdot, c, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    wdot[id] *= 1.0e-6;
  }
}

// Returns the molar production rate of species
// Given rho, T, and mole fractions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKWXR(
  const amrex::Real rho,
  const amrex::Real T,
  const amrex::Real x[],
  amrex::Real wdot[])
{
  amrex::Real c[5];   // temporary storage
  amrex::Real XW = 0; // See Eq 4, 11 in CK Manual
  amrex::Real ROW;
  // Compute mean molecular wt first
  XW += x[0] * 3.1998000000000001e+01; // O2
  XW += x[1] * 1.8015000000000001e+01; // H2O
  XW += x[2] * 1.6042999999999999e+01; // CH4
  XW += x[3] * 4.4009000000000000e+01; // CO2
  XW += x[4] * 2.8013999999999999e+01; // N2
  // Extra 1e6 factor to take c to SI
  ROW = 1e6 * rho / XW;

  // Compute conversion, see Eq 11
  for (int id = 0; id < 5; ++id) {
    c[id] = x[id] * ROW;
  }

  // convert to chemkin units
  productionRate(wdot, c, T);

  // convert to chemkin units
  for (int id = 0; id < 5; ++id) {
    wdot[id] *= 1.0e-6;
  }
}

//  species unit charge number
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCHRG(int kcharge[])
{
  kcharge[0] = 0; // O2
  kcharge[1] = 0; // H2O
  kcharge[2] = 0; // CH4
  kcharge[3] = 0; // CO2
  kcharge[4] = 0; // N2
}

//  species charge per unit mass
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
CKCHRGMASS(amrex::Real zk[])
{

  int kchrg[5];
  CKCHRG(kchrg);

  for (int id = 0; id < 5; ++id) {
    zk[id] = 6.02214076e+23 * 1.60217663e-19 * kchrg[id] * imw(id);
  }
}

// compute an approx to the reaction Jacobian
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
aJacobian_precond(
  amrex::Real* J, const amrex::Real* sc, const amrex::Real T, const int HP)
{

#if defined(PELE_COMPILE_AJACOBIAN) || !defined(AMREX_USE_HIP)
  for (int i = 0; i < 36; i++) {
    J[i] = 0.0;
  }

  amrex::Real wdot[5];
  for (auto& val : wdot) {
    val = 0.0;
  }

  const amrex::Real invT = 1.0 / T;
  const amrex::Real invT2 = invT * invT;
  const amrex::Real logT = log(T);

  // reference concentration: P_atm / (RT) in inverse mol/m^3
  amrex::Real refC = 101325 / 8.31446 / T;
  amrex::Real refCinv = 1.0 / refC;

  // compute the mixture concentration
  amrex::Real mixture = 0.0;
  for (int k = 0; k < 5; ++k) {
    mixture += sc[k];
  }

  // compute the Gibbs free energy
  amrex::Real g_RT[5];
  gibbs(g_RT, T);

  // compute the species enthalpy
  amrex::Real h_RT[5];
  speciesEnthalpy(h_RT, T);

  amrex::Real phi_f, k_f, k_r, phi_r, Kc, q, q_nocor, Corr, alpha;
  amrex::Real dlnkfdT, dlnk0dT, dlnKcdT, dkrdT, dqdT;
  amrex::Real dqdci, dcdc_fac, dqdc[5];
  amrex::Real Pr, fPr, F, k_0, logPr;
  amrex::Real logFcent, troe_c, troe_n, troePr_den, troePr, troe;
  amrex::Real Fcent1, Fcent2, Fcent3, Fcent;
  amrex::Real dlogFdc, dlogFdn, dlogFdcn_fac;
  amrex::Real dlogPrdT, dlogfPrdT, dlogFdT, dlogFcentdT, dlogFdlogPr, dlnCorrdT;
  const amrex::Real ln10 = log(10.0);
  const amrex::Real log10e = 1.0 / log(10.0);
  // reaction 0: CH4 + 2 O2 => CO2 + 2 H2O
  // a non-third-body and non-pressure-fall-off reaction
  // forward
  phi_f = sc[0] * sc[2];
  k_f = 1000;
  dlnkfdT = 0.0;
  // rate of progress
  q = k_f * phi_f;
  dqdT = dlnkfdT * k_f * phi_f;
  // update wdot
  wdot[0] -= 2 * q; // O2
  wdot[1] += 2 * q; // H2O
  wdot[2] -= q;     // CH4
  wdot[3] += q;     // CO2
  // d()/d[O2]
  dqdci = +k_f * sc[2];
  J[0] += -2 * dqdci; // dwdot[O2]/d[O2]
  J[1] += 2 * dqdci;  // dwdot[H2O]/d[O2]
  J[2] -= dqdci;      // dwdot[CH4]/d[O2]
  J[3] += dqdci;      // dwdot[CO2]/d[O2]
  // d()/d[CH4]
  dqdci = +k_f * sc[0];
  J[12] += -2 * dqdci; // dwdot[O2]/d[CH4]
  J[13] += 2 * dqdci;  // dwdot[H2O]/d[CH4]
  J[14] -= dqdci;      // dwdot[CH4]/d[CH4]
  J[15] += dqdci;      // dwdot[CO2]/d[CH4]
  // d()/dT
  J[30] += -2 * dqdT; // dwdot[O2]/dT
  J[31] += 2 * dqdT;  // dwdot[H2O]/dT
  J[32] -= dqdT;      // dwdot[CH4]/dT
  J[33] += dqdT;      // dwdot[CO2]/dT

  amrex::Real c_R[5], dcRdT[5], e_RT[5];
  amrex::Real* eh_RT;
  if (HP == 1) {
    cp_R(c_R, T);
    dcvpRdT(dcRdT, T);
    eh_RT = &h_RT[0];
  } else {
    cv_R(c_R, T);
    dcvpRdT(dcRdT, T);
    speciesInternalEnergy(e_RT, T);
    eh_RT = &e_RT[0];
  }

  amrex::Real cmix = 0.0, ehmix = 0.0, dcmixdT = 0.0, dehmixdT = 0.0;
  for (int k = 0; k < 5; ++k) {
    cmix += c_R[k] * sc[k];
    dcmixdT += dcRdT[k] * sc[k];
    ehmix += eh_RT[k] * wdot[k];
    dehmixdT += invT * (c_R[k] - eh_RT[k]) * wdot[k] + eh_RT[k] * J[30 + k];
  }

  amrex::Real cmixinv = 1.0 / cmix;
  amrex::Real tmp1 = ehmix * cmixinv;
  amrex::Real tmp3 = cmixinv * T;
  amrex::Real tmp2 = tmp1 * tmp3;
  amrex::Real dehmixdc;
  // dTdot/d[X]
  for (int k = 0; k < 5; ++k) {
    dehmixdc = 0.0;
    for (int m = 0; m < 5; ++m) {
      dehmixdc += eh_RT[m] * J[k * 6 + m];
    }
    J[k * 6 + 5] = tmp2 * c_R[k] - tmp3 * dehmixdc;
  }
  // dTdot/dT
  J[35] = -tmp1 + tmp2 * dcmixdT - tmp3 * dehmixdT;
#else
  amrex::Abort();
#endif
}

// compute an approx to the reaction Jacobian (for preconditioning)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
DWDOT_SIMPLIFIED(
  amrex::Real* J, const amrex::Real* sc, const amrex::Real* Tp, const int* HP)
{
  amrex::Real c[5];

  for (int k = 0; k < 5; k++) {
    c[k] = 1.e6 * sc[k];
  }

  aJacobian_precond(J, c, *Tp, *HP);

  // dwdot[k]/dT
  // dTdot/d[X]
  for (int k = 0; k < 5; k++) {
    J[30 + k] *= 1.e-6;
    J[k * 6 + 5] *= 1.e6;
  }
}

// compute the reaction Jacobian
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
aJacobian(
  amrex::Real* J, const amrex::Real* sc, const amrex::Real T, const int consP)
{

#if defined(PELE_COMPILE_AJACOBIAN) || !defined(AMREX_USE_HIP)
  for (int i = 0; i < 36; i++) {
    J[i] = 0.0;
  }

  amrex::Real wdot[5];
  for (auto& val : wdot) {
    val = 0.0;
  }

  const amrex::Real invT = 1.0 / T;
  const amrex::Real invT2 = invT * invT;
  const amrex::Real logT = log(T);

  // reference concentration: P_atm / (RT) in inverse mol/m^3
  amrex::Real refC = 101325 / 8.31446 / T;
  amrex::Real refCinv = 1.0 / refC;

  // compute the mixture concentration
  amrex::Real mixture = 0.0;
  for (int k = 0; k < 5; ++k) {
    mixture += sc[k];
  }

  // compute the Gibbs free energy
  amrex::Real g_RT[5];
  gibbs(g_RT, T);

  // compute the species enthalpy
  amrex::Real h_RT[5];
  speciesEnthalpy(h_RT, T);

  amrex::Real phi_f, k_f, k_r, phi_r, Kc, q, q_nocor, Corr, alpha;
  amrex::Real dlnkfdT, dlnk0dT, dlnKcdT, dkrdT, dqdT;
  amrex::Real dqdci, dcdc_fac, dqdc[5];
  amrex::Real Pr, fPr, F, k_0, logPr;
  amrex::Real logFcent, troe_c, troe_n, troePr_den, troePr, troe;
  amrex::Real Fcent1, Fcent2, Fcent3, Fcent;
  amrex::Real dlogFdc, dlogFdn, dlogFdcn_fac;
  amrex::Real dlogPrdT, dlogfPrdT, dlogFdT, dlogFcentdT, dlogFdlogPr, dlnCorrdT;
  const amrex::Real ln10 = log(10.0);
  const amrex::Real log10e = 1.0 / log(10.0);
  // reaction 0: CH4 + 2 O2 => CO2 + 2 H2O
  // a non-third-body and non-pressure-fall-off reaction
  // forward
  phi_f = sc[0] * sc[2];
  k_f = 1000;
  dlnkfdT = 0.0;
  // rate of progress
  q = k_f * phi_f;
  dqdT = dlnkfdT * k_f * phi_f;
  // update wdot
  wdot[0] -= 2 * q; // O2
  wdot[1] += 2 * q; // H2O
  wdot[2] -= q;     // CH4
  wdot[3] += q;     // CO2
  // d()/d[O2]
  dqdci = +k_f * sc[2];
  J[0] += -2 * dqdci; // dwdot[O2]/d[O2]
  J[1] += 2 * dqdci;  // dwdot[H2O]/d[O2]
  J[2] -= dqdci;      // dwdot[CH4]/d[O2]
  J[3] += dqdci;      // dwdot[CO2]/d[O2]
  // d()/d[CH4]
  dqdci = +k_f * sc[0];
  J[12] += -2 * dqdci; // dwdot[O2]/d[CH4]
  J[13] += 2 * dqdci;  // dwdot[H2O]/d[CH4]
  J[14] -= dqdci;      // dwdot[CH4]/d[CH4]
  J[15] += dqdci;      // dwdot[CO2]/d[CH4]
  // d()/dT
  J[30] += -2 * dqdT; // dwdot[O2]/dT
  J[31] += 2 * dqdT;  // dwdot[H2O]/dT
  J[32] -= dqdT;      // dwdot[CH4]/dT
  J[33] += dqdT;      // dwdot[CO2]/dT

  amrex::Real c_R[5], dcRdT[5], e_RT[5];
  amrex::Real* eh_RT;
  if (consP == 1) {
    cp_R(c_R, T);
    dcvpRdT(dcRdT, T);
    eh_RT = &h_RT[0];
  } else {
    cv_R(c_R, T);
    dcvpRdT(dcRdT, T);
    speciesInternalEnergy(e_RT, T);
    eh_RT = &e_RT[0];
  }

  amrex::Real cmix = 0.0, ehmix = 0.0, dcmixdT = 0.0, dehmixdT = 0.0;
  for (int k = 0; k < 5; ++k) {
    cmix += c_R[k] * sc[k];
    dcmixdT += dcRdT[k] * sc[k];
    ehmix += eh_RT[k] * wdot[k];
    dehmixdT += invT * (c_R[k] - eh_RT[k]) * wdot[k] + eh_RT[k] * J[30 + k];
  }

  amrex::Real cmixinv = 1.0 / cmix;
  amrex::Real tmp1 = ehmix * cmixinv;
  amrex::Real tmp3 = cmixinv * T;
  amrex::Real tmp2 = tmp1 * tmp3;
  amrex::Real dehmixdc;
  // dTdot/d[X]
  for (int k = 0; k < 5; ++k) {
    dehmixdc = 0.0;
    for (int m = 0; m < 5; ++m) {
      dehmixdc += eh_RT[m] * J[k * 6 + m];
    }
    J[k * 6 + 5] = tmp2 * c_R[k] - tmp3 * dehmixdc;
  }
  // dTdot/dT
  J[35] = -tmp1 + tmp2 * dcmixdT - tmp3 * dehmixdT;
#else
  amrex::Abort();
#endif
}

// compute the reaction Jacobian
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
DWDOT(
  amrex::Real* J,
  const amrex::Real* sc,
  const amrex::Real* Tp,
  const int* consP)
{
  amrex::Real c[5];

  for (int k = 0; k < 5; k++) {
    c[k] = 1.e6 * sc[k];
  }

  aJacobian(J, c, *Tp, *consP);

  // dwdot[k]/dT
  // dTdot/d[X]
  for (int k = 0; k < 5; k++) {
    J[30 + k] *= 1.e-6;
    J[k * 6 + 5] *= 1.e6;
  }
}

// Transport function declarations

AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetLENIMC(int* LENIMC)
{
  *LENIMC = 20;
}

AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetLENRMC(int* LENRMC)
{
  *LENRMC = 610;
}

AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetNO(int* NO)
{
  *NO = 4;
}

AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetKK(int* KK)
{
  *KK = 5;
}

AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetNLITE(int* NLITE)
{
  *NLITE = 0;
}

// Patm in ergs/cm3
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetPATM(amrex::Real* PATM)
{
  *PATM = 0.1013250000000000E+07;
}

// the molecular weights in g/mol
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetWT(amrex::Real* WT)
{
  WT[0] = 3.19980000E+01;
  WT[1] = 1.80150000E+01;
  WT[2] = 1.60430000E+01;
  WT[3] = 4.40090000E+01;
  WT[4] = 2.80140000E+01;
}

// the lennard-jones potential well depth eps/kb in K
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetEPS(amrex::Real* EPS)
{
  EPS[0] = 1.07400000E+02;
  EPS[1] = 5.72400000E+02;
  EPS[2] = 1.41500000E+02;
  EPS[3] = 2.44000000E+02;
  EPS[4] = 9.75300000E+01;
}

// the lennard-jones collision diameter in Angstroms
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetSIG(amrex::Real* SIG)
{
  SIG[0] = 3.45800000E+00;
  SIG[1] = 2.60500000E+00;
  SIG[2] = 3.75800000E+00;
  SIG[3] = 3.76300000E+00;
  SIG[4] = 3.62100000E+00;
}

// the dipole moment in Debye
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetDIP(amrex::Real* DIP)
{
  DIP[0] = 0.00000000E+00;
  DIP[1] = 1.84400000E+00;
  DIP[2] = 0.00000000E+00;
  DIP[3] = 0.00000000E+00;
  DIP[4] = 0.00000000E+00;
}

// the polarizability in cubic Angstroms
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetPOL(amrex::Real* POL)
{
  POL[0] = 1.60000000E+00;
  POL[1] = 0.00000000E+00;
  POL[2] = 2.60000000E+00;
  POL[3] = 2.65000000E+00;
  POL[4] = 1.76000000E+00;
}

// the rotational relaxation collision number at 298 K
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetZROT(amrex::Real* ZROT)
{
  ZROT[0] = 3.80000000E+00;
  ZROT[1] = 4.00000000E+00;
  ZROT[2] = 1.30000000E+01;
  ZROT[3] = 2.10000000E+00;
  ZROT[4] = 4.00000000E+00;
}

// 0: monoatomic, 1: linear, 2: nonlinear
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetNLIN(int* NLIN)
{
  NLIN[0] = 1;
  NLIN[1] = 2;
  NLIN[2] = 2;
  NLIN[3] = 1;
  NLIN[4] = 1;
}

// Poly fits for the viscosities, dim NO*KK
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetCOFETA(amrex::Real* COFETA)
{
  COFETA[0] = -1.78915955E+01;
  COFETA[1] = 2.98311502E+00;
  COFETA[2] = -3.14105508E-01;
  COFETA[3] = 1.40500162E-02;
  COFETA[4] = -1.14441704E+01;
  COFETA[5] = -9.67162726E-01;
  COFETA[6] = 3.58651315E-01;
  COFETA[7] = -2.09789188E-02;
  COFETA[8] = -2.04751621E+01;
  COFETA[9] = 3.75522597E+00;
  COFETA[10] = -4.11946038E-01;
  COFETA[11] = 1.81840504E-02;
  COFETA[12] = -2.28110458E+01;
  COFETA[13] = 4.62954710E+00;
  COFETA[14] = -5.00689001E-01;
  COFETA[15] = 2.10012969E-02;
  COFETA[16] = -1.73976840E+01;
  COFETA[17] = 2.73482764E+00;
  COFETA[18] = -2.81916034E-01;
  COFETA[19] = 1.26588405E-02;
}

// Poly fits for the conductivities, dim NO*KK
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetCOFLAM(amrex::Real* COFLAM)
{
  COFLAM[0] = 7.13715609E-01;
  COFLAM[1] = 1.79167550E+00;
  COFLAM[2] = -1.20340496E-01;
  COFLAM[3] = 4.69808739E-03;
  COFLAM[4] = 1.78984926E+01;
  COFLAM[5] = -6.62285295E+00;
  COFLAM[6] = 1.19609125E+00;
  COFLAM[7] = -6.02372587E-02;
  COFLAM[8] = 1.62680262E+01;
  COFLAM[9] = -6.01630626E+00;
  COFLAM[10] = 1.14990881E+00;
  COFLAM[11] = -6.01896937E-02;
  COFLAM[12] = -8.59234014E+00;
  COFLAM[13] = 4.72899549E+00;
  COFLAM[14] = -4.10258362E-01;
  COFLAM[15] = 1.31618557E-02;
  COFLAM[16] = 8.49629659E+00;
  COFLAM[17] = -1.61118438E+00;
  COFLAM[18] = 3.70611059E-01;
  COFLAM[19] = -1.88601707E-02;
}

// Poly fits for the diffusion coefficients, dim NO*KK*KK
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetCOFD(amrex::Real* COFD)
{
  COFD[0] = -1.60936459E+01;
  COFD[1] = 3.70633871E+00;
  COFD[2] = -2.71897253E-01;
  COFD[3] = 1.20097588E-02;
  COFD[4] = -1.99035490E+01;
  COFD[5] = 5.01694632E+00;
  COFD[6] = -4.08962988E-01;
  COFD[7] = 1.66143402E-02;
  COFD[8] = -1.16123739E+01;
  COFD[9] = 8.27753087E-01;
  COFD[10] = 2.52262500E-01;
  COFD[11] = -1.62567542E-02;
  COFD[12] = -1.68154222E+01;
  COFD[13] = 4.01402516E+00;
  COFD[14] = -3.10567507E-01;
  COFD[15] = 1.36320866E-02;
  COFD[16] = -1.95714648E+01;
  COFD[17] = 4.78959118E+00;
  COFD[18] = -3.66233634E-01;
  COFD[19] = 1.42353730E-02;
  COFD[20] = -1.75719115E+01;
  COFD[21] = 4.30742480E+00;
  COFD[22] = -3.46634706E-01;
  COFD[23] = 1.51126657E-02;
  COFD[24] = -1.87633989E+01;
  COFD[25] = 4.61060397E+00;
  COFD[26] = -3.83564503E-01;
  COFD[27] = 1.66168246E-02;
  COFD[28] = -1.82187534E+01;
  COFD[29] = 3.93854125E+00;
  COFD[30] = -2.28424577E-01;
  COFD[31] = 7.18603064E-03;
  COFD[32] = -1.93984699E+01;
  COFD[33] = 4.87193388E+00;
  COFD[34] = -4.13370021E-01;
  COFD[35] = 1.77422903E-02;
  COFD[36] = -2.05810575E+01;
  COFD[37] = 5.07469434E+00;
  COFD[38] = -4.25340301E-01;
  COFD[39] = 1.76800795E-02;
  COFD[40] = -1.58214949E+01;
  COFD[41] = 3.60000113E+00;
  COFD[42] = -2.58255120E-01;
  COFD[43] = 1.14251480E-02;
  COFD[44] = -1.99472346E+01;
  COFD[45] = 5.05636620E+00;
  COFD[46] = -4.17733674E-01;
  COFD[47] = 1.71403498E-02;
  COFD[48] = -1.65758222E+01;
  COFD[49] = 3.92071372E+00;
  COFD[50] = -2.99120887E-01;
  COFD[51] = 1.31639914E-02;
  COFD[52] = -1.85068911E+01;
  COFD[53] = 4.52122572E+00;
  COFD[54] = -3.73088946E-01;
  COFD[55] = 1.62076520E-02;
  COFD[56] = -1.56019684E+01;
  COFD[57] = 3.51542686E+00;
  COFD[58] = -2.47677471E-01;
  COFD[59] = 1.09841319E-02;
}

// List of specs with small weight, dim NLITE
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetKTDIF(int* /*KTDIF*/)
{
}

// Poly fits for thermal diff ratios, dim NO*NLITE*KK
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
egtransetCOFTD(amrex::Real* /*COFTD*/)
{
}

// compute the critical parameters for each species
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
GET_CRITPARAMS(
  amrex::Real* Tci, amrex::Real* ai, amrex::Real* bi, amrex::Real* acentric_i)
{

  amrex::Real EPS[5];
  amrex::Real SIG[5];
  amrex::Real wt[5];
  amrex::Real Rcst = 83.144598; // in bar [CGS] !

  egtransetEPS(EPS);
  egtransetSIG(SIG);
  get_mw(wt);

  // species 0: O2
  // Imported from NIST
  Tci[0] = 154.581000;
  ai[0] = 1e6 * 0.42748 * Rcst * Rcst * Tci[0] * Tci[0] /
          (31.998800 * 31.998800 * 50.430466);
  bi[0] = 0.08664 * Rcst * Tci[0] / (31.998800 * 50.430466);
  acentric_i[0] = 0.022200;

  // species 1: H2O
  // Imported from NIST
  Tci[1] = 647.096000;
  ai[1] = 1e6 * 0.42748 * Rcst * Rcst * Tci[1] * Tci[1] /
          (18.015340 * 18.015340 * 220.640000);
  bi[1] = 0.08664 * Rcst * Tci[1] / (18.015340 * 220.640000);
  acentric_i[1] = 0.344300;

  // species 2: CH4
  // Imported from NIST
  Tci[2] = 190.560000;
  ai[2] = 1e6 * 0.42748 * Rcst * Rcst * Tci[2] * Tci[2] /
          (16.043030 * 16.043030 * 45.990000);
  bi[2] = 0.08664 * Rcst * Tci[2] / (16.043030 * 45.990000);
  acentric_i[2] = 0.011000;

  // species 3: CO2
  // Imported from NIST
  Tci[3] = 304.120000;
  ai[3] = 1e6 * 0.42748 * Rcst * Rcst * Tci[3] * Tci[3] /
          (44.009950 * 44.009950 * 73.740000);
  bi[3] = 0.08664 * Rcst * Tci[3] / (44.009950 * 73.740000);
  acentric_i[3] = 0.225000;

  // species 4: N2
  // Imported from NIST
  Tci[4] = 126.192000;
  ai[4] = 1e6 * 0.42748 * Rcst * Rcst * Tci[4] * Tci[4] /
          (28.013400 * 28.013400 * 33.958000);
  bi[4] = 0.08664 * Rcst * Tci[4] / (28.013400 * 33.958000);
  acentric_i[4] = 0.037200;
}

// compute the critical parameter quantities for each species for SRK
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
GET_CRITPARAMS_SRK(
  amrex::Real* sqrtOneOverTc,
  amrex::Real* sqrtAsti,
  amrex::Real* Bi,
  amrex::Real* Fomega)
{

  // species 0: O2
  // Imported from NIST
  sqrtOneOverTc[0] = 8.0430717653241e-02;
  sqrtAsti[0] = 3.6980081924740e+04;
  Bi[0] = 6.9005216444999e-01;
  Fomega[0] = 5.1945301904908e-01;

  // species 1: H2O
  // Imported from NIST
  sqrtOneOverTc[1] = 3.9311140369715e-02;
  sqrtAsti[1] = 1.3145468419592e+05;
  Bi[1] = 1.1727204136223e+00;
  Fomega[1] = 1.0013577274636e+00;

  // species 2: CH4
  // Imported from NIST
  sqrtOneOverTc[2] = 7.2440948474968e-02;
  sqrtAsti[2] = 9.5215046085708e+04;
  Bi[2] = 1.8605203320660e+00;
  Fomega[2] = 5.0213035482700e-01;

  // species 3: CO2
  // Imported from NIST
  sqrtOneOverTc[3] = 5.7342616962522e-02;
  sqrtAsti[3] = 4.3745610142919e+04;
  Bi[3] = 6.7506167841745e-01;
  Fomega[3] = 8.2653709187500e-01;

  // species 4: N2
  // Imported from NIST
  sqrtOneOverTc[4] = 8.9019282240563e-02;
  sqrtAsti[4] = 4.2022983929562e+04;
  Bi[4] = 9.5560052221563e-01;
  Fomega[4] = 5.4259343186608e-01;
}

// gauss-jordan solver external routine
// Replace this routine with the one generated by the Gauss Jordan solver of DW
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
sgjsolve(amrex::Real* /*A*/, amrex::Real* /*x*/, amrex::Real* /*b*/)
{
  amrex::Abort("sgjsolve not implemented, choose a different solver ");
}

// Replace this routine with the one generated by the Gauss Jordan solver of DW
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void
sgjsolve_simplified(amrex::Real* /*A*/, amrex::Real* /*x*/, amrex::Real* /*b*/)
{
  amrex::Abort(
    "sgjsolve_simplified not implemented, choose a different solver ");
}

#endif
